"""made changes in comment

Revision ID: 14672947838c
Revises: 5439bf3bc2b8
Create Date: 2025-04-09 13:01:23.474662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14672947838c'
down_revision = '5439bf3bc2b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_comments_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
