"""initial migration

Revision ID: 8e3720d04cee
Revises: 4050acb151ae
Create Date: 2025-04-08 21:50:31.606942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3720d04cee'
down_revision = '4050acb151ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_comments_user_id_users',  # ✅ Give it a name
            'users',                      # Referenced table
            ['user_id'],                  # Local column
            ['id']                        # Referenced column
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comments_user_id_users', type_='foreignkey')  # ✅ Use the same name
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
